### ISSUE TITLE
Make a Database Map

### ISSUE THREAD

**Issue by ChrisFischer-MTA** [ChrisFischer-MTA/COP4331_Project-1#2]
Make a database map. This map should contain several objects:

User object
Field Examples:
(Name, Username, Password, Date Created, Last Password Change, User ID)

Contact Object:
Field Examples:
Name
Phone Number
Photo
Notes

**Comment by Bpurden** [comment]
[Database ER diagram Small Project.pdf](https://github.com/ChrisFischer-MTA/COP4331_Project-1/files/7069807/Database.ER.diagram.Small.Project.pdf)

**Comment by Bpurden** [comment]
![Database Small Project](https://user-images.githubusercontent.com/89457788/131198836-099e5ce9-9cf0-4261-84e5-79ed794f5ffe.png)

**Comment by plmwd** [comment]
Seems to be working fine - closing.
