### ISSUE TITLE
Make API Outline

### ISSUE THREAD

**Issue by ChrisFischer-MTA** [ChrisFischer-MTA/COP4331_Project-1#3]
The API outline should have methods to Create, Read, Update, and Delete both Users and Contacts in the contact manager. A good example is the discord API. The API will exist on the server, take in and spit out JSON files.

https://discord.com/developers/docs/reference

**Comment by ChrisFischer-MTA** [comment]
Two examples of how a function definition in the API might look like:

![image](https://user-images.githubusercontent.com/11450403/130656976-76aed944-1ff1-4621-9792-67b5d5290c15.png)

![image](https://user-images.githubusercontent.com/11450403/130657032-02a54ca8-d460-4003-bbc0-5e3f813bea8f.png)

Also prepare to re-write this as we get more information from the DB and Frontend Team.

**Comment by RPenrose1** [comment]
[APIroughDraft.pdf](https://github.com/ChrisFischer-MTA/COP4331_Project-1/files/7070806/APIroughDraft.pdf)
Almost forgot to upload the update. Slight changes made using Paul's suggestions.

**Comment by plmwd** [comment]
> [API Rough Draft(Put and Delete).pdf](https://github.com/ChrisFischer-MTA/COP4331_Project-1/files/7068998/API.Rough.Draft.Put.and.Delete.pdf)
> This is my rough draft for the put and delete APIs

The **_delete_** endpoint for deleting the account, which we can keep, but we also need a endpoint for deleting a contact. 
Something like this:
**Input**
``` json
{
    "contactIDs": [4, 2, 0]
}
```

**Output**
``` json
{
    "failure": "Empty if successful, or error message"
}
```

As for **__update__**, it should include all of the following fields (if a empty string the back-end should ignore updating that field):
* First name
* Last name
* Date of birth
* Street address 1
* Street address 2
* City
* State
* Zip code
* Phone number
* Relationship
* Profession
* Notes 

Also, what is the front end going to be doing with the sessionID? Shouldn't it be sending the sessionID (assuming the user is already authenticated) with each API call?

**Comment by plmwd** [comment]
> [APIroughDraft.pdf](https://github.com/ChrisFischer-MTA/COP4331_Project-1/files/7070806/APIroughDraft.pdf)
> Almost forgot to upload the update. Slight changes made using Paul's suggestions.

What do you think about making **__read__** accept a list of IDs? If there is time, it could more easily allow for the front end to do opportunistic loading of contacts, or to load contacts in chunks.

**Comment by JasonD122** [comment]
Yeaaaa I wasn’t 100% sure what the session ID was I thought was it like a new page you get after so you can see the update

**Comment by JasonD122** [comment]
And I wasn’t sure what information we were taking

**Comment by JasonD122** [comment]
I’ll make those changes

**Comment by JasonD122** [comment]
Also if anyone is available tomorrow to go over some of the API stuff with me so I have a better understanding I would appreciate it

**Comment by plmwd** [comment]
Yeah, let's meet tomorrow.

**Comment by ChrisFischer-MTA** [comment]
Need you guys to add methods to remove contacts.

**Comment by JasonD122** [comment]
Doing that now

**Comment by RPenrose1** [comment]
> > [APIroughDraft.pdf](https://github.com/ChrisFischer-MTA/COP4331_Project-1/files/7070806/APIroughDraft.pdf)
> > Almost forgot to upload the update. Slight changes made using Paul's suggestions.
> 
> What do you think about making **_read_** accept a list of IDs? If there is time, it could more easily allow for the front end to do opportunistic loading of contacts, or to load contacts in chunks.

read.php is simply to provide the user info on a singular contact when you click their name. The click is required from the user to utilize read.php, so I'm not exactly certain how we would send a list of ID's since you can only click on one name at a time.

**Comment by plmwd** [comment]
It's so you can load more contacts with less GETs, and it'll cache the data. Like, when you're viewing the main contact page, you'll see N contacts in the list on the left-hand column, so the front end can go ahead and request for those N contacts so it's quicker to load them. I was thinking it'll be dynamic, instead of the page reloading every time you click on a contact on the left.

**Comment by RPenrose1** [comment]
> It's so you can load more contacts with less GETs, and it'll cache the data. Like, when you're viewing the main contact page, you'll see N contacts in the list on the left-hand column, so the front end can go ahead and request for those N contacts so it's quicker to load them. I was thinking it'll be dynamic, instead of the page reloading every time you click on a contact on the left.
> 
> It could just be premature optimization... lol

So if Im understanding your suggestion, we have read.php send all requested contacts a user requires on a search and the front end will hold that info in the background? Cause what you're suggesting to avoid using more GET actions is grabbing all the data from the database now so we won't have to deal with the data after that.
While I have no problem with that, I'm concerned it will create more work for both the front end team and the database guy

**Comment by JasonD122** [comment]
How does it look like in the front end for the contacts. I mean we can do it like in multiples of 5-10 maybe??

**Comment by plmwd** [comment]
> > It's so you can load more contacts with less GETs, and it'll cache the data. Like, when you're viewing the main contact page, you'll see N contacts in the list on the left-hand column, so the front end can go ahead and request for those N contacts so it's quicker to load them. I was thinking it'll be dynamic, instead of the page reloading every time you click on a contact on the left.
> 
> > 
> 
> > It could just be premature optimization... lol
> 
> 
> 
> So if Im understanding your suggestion, we have read.php send all requested contacts a user requires on a search and the front end will hold that info in the background? Cause what you're suggesting to avoid using more GET actions is grabbing all the data from the database now so we won't have to deal with the data after that.
> 
> While I have no problem with that, I'm concerned it will create more work for both the front end team and the database guy. Front end because you guys will have to store that without displaying it and backend cause he'll need to be able to run through the JSON request from the API where it won't be told how many contacts to grab

We can keep this on the back burner and keep read how it is now so we can have a MVP  and do improvements later.

**Comment by plmwd** [comment]
If we get time, it can be a new endpoint called batchRead or something. 

Also, for the sake of keeping things simple, would it be easier or harder for the backend to return all of the contact info on the search endpoint rather than the IDs?

**Comment by RPenrose1** [comment]
[APIroughDraft.docx](https://github.com/ChrisFischer-MTA/COP4331_Project-1/files/7139681/APIroughDraft.docx)
[APIroughDraft.pdf](https://github.com/ChrisFischer-MTA/COP4331_Project-1/files/7139682/APIroughDraft.pdf)
Slight update as per Chris' request

**Comment by plmwd** [comment]
What was the change?

**Comment by plmwd** [comment]
https://app.swaggerhub.com/apis/rpenrose/ContactManagerAPI/1.0.0#/

**Comment by RPenrose1** [comment]
> What was the change?

Sorry, github didn't notify me of this question. Simple change on deleteContact to display input as an array rather than a list of numbers.

Also login API is functional as of yesterday

**Comment by plmwd** [comment]
Project finished.
