### ISSUE TITLE
Make UX Design

### ISSUE THREAD

**Issue by ChrisFischer-MTA** [ChrisFischer-MTA/COP4331_Project-1#4]
Make a mock up of what you'd want the website to look like. This should be a few pages (hand drawn) showing a rough outline of where you'd want the buttons, what the buttons would look like, what the page looks like, where we stick text, all of that. We'll reference in when building the front end.

The pages that require mock up:
- Login Page
- Registration Page
- Index view (view a list of contacts)
- Detail view of a specific contact

**Comment by ChrisFischer-MTA** [comment]
I'd encourage you to look up similar web based contact managers and take inspiration

**Comment by plmwd** [comment]
I'm working on the design on [this](https://www.figma.com/file/iWmaTBVZeWz0aOYsa12CQJ/COP4331_Project-1?node-id=1%3A3) website.

Here's some inspriation I'm using:
* https://www.reallysimplesystems.com/crm-features/
* https://www.copper.com/contact-management-software
* https://www.contactsplus.com/

**Comment by plmwd** [comment]
![COP4331_Project-1](https://user-images.githubusercontent.com/5152848/131255912-21fe76c4-9fa9-4b01-92a1-13951523bd80.png)

**Comment by ChrisFischer-MTA** [comment]
Fantastic. A new issue will be created shortly with new tasking for the UI team.
