### ISSUE TITLE
Create the front end.

### ISSUE THREAD

**Issue by ChrisFischer-MTA** [ChrisFischer-MTA/COP4331_Project-1#5]
Create the front end. You should implement the API as described in the API issue.

**Comment by ChrisFischer-MTA** [comment]
Notes:
- Create a button for "Forgot your password". It will retrieve a password hint.
- There should be a panel for users to update _their_ information, as if it were a contact. (I'd recommend the first contact be their information)

**Comment by plmwd** [comment]
Merging login-page and contacts-manager-page today.
