### ISSUE TITLE
Database Is made

### ISSUE THREAD

**Issue by Bpurden** [ChrisFischer-MTA/COP4331_Project-1#6]
![Database](https://user-images.githubusercontent.com/89457788/131498574-60a14c26-9e74-4fcf-89f2-c8e9adeabb3c.PNG)

**Comment by Bpurden** [comment]
login: root
password: cop4331FP

ip address
-------------
67.205.134.243

This is the user that has permissions to the Database
-----------------------------------------------------------------------------
create user 'TheBeast' identified by 'WeLoveCOP4331';
Now we need to grant permissions to the database for that user:
grant all privileges on COP4331.* to 'TheBeast'@'%';

**Comment by ChrisFischer-MTA** [comment]
Did you put this on a new instance?

**Comment by Bpurden** [comment]
Yes

**Comment by plmwd** [comment]
Database works - closing.
