### ISSUE TITLE
Login API

### ISSUE THREAD

**Issue by plmwd** [ChrisFischer-MTA/COP4331_Project-1#7]
Creating this issue to track the login api endpoint. What's the current status?

**Comment by JasonD122** [comment]
I’ll have it down by tomorrow before class. I have a couple things to do today. Also can you all Dm me the username password and database name for the Database. If it’s the same as the word document he created just say it’s the same

**Comment by plmwd** [comment]
Works - see #9 for tests and #3 for swaggerhub.
